[[user-guide]]
= MyBatis Thymeleaf User's Guide
:author: The MyBatis Team
:revnumber: 1.0.0-SNAPSHOT
:revdate: {localdate}
:toc: left
:icons: font
:source-highlighter: coderay
:imagesdir: ./images
:imagesoutdir: ./images
:docinfodir: ./docinfos
:docinfo1:
:sectnums:
:nofooter:
:sectlinks:
:linkcss:
:xrefstyle: full

// Define variable for urls
:mybatis-doc-url: http://www.mybatis.org/mybatis-3
:travis-ci-url: https://travis-ci.org/mybatis/thymeleaf-scripting
:mybatis-spring-boot-doc-url: http://www.mybatis.org/spring-boot-starter
:thymeleaf-doc-url: https://www.thymeleaf.org/doc/tutorials/3.0
:github-organization-url: https://github.com/mybatis

== Overview

=== What is MyBatis Thymeleaf ?

The mybatis-thymeleaf is a plugin that helps applying the 2-way SQL/dynamic SQL feature to the MyBatis 3
using the template(or natural template) mechanism provided by Thymeleaf 3.
If you are not familiar with MyBatis and Thymeleaf, you can see following official documentations.

* {mybatis-doc-url}[MyBatis 3 REFERENCE DOCUMENTATION^]
* {thymeleaf-doc-url}/usingthymeleaf.html[Tutorial: Using Thymeleaf^]
* {thymeleaf-doc-url}/usingthymeleaf.html#textual-template-modes[Tutorial: Using Thymeleaf -13 Textual template modes-^]

=== What is 2-way SQL/Dynamic SQL ?

The 2-way SQL can be used by following *two way*.

* It can be executed as-is in SQL execution tool (such as psql, mysql, sqlplus, plugins for IDE, etc...)
* It can be used as a SQL template for creating a bindable and dynamically SQL on your application

==== Simple bindable 2-way SQL

The mybatis-thymeleaf translate a simple bindable 2-way SQL that specified by natural template to as follow:

[source,sql]
.Natural template
----
SELECT * FROM names
  WHERE id = /*[('#{id}')]*/ 1
----

[source,sql]
.Translated to SQL that can parse in MyBatis by Thymeleaf processing
----
SELECT * FROM names
  WHERE id = #{id}
----

[source,sql]
.Translated to SQL that can parse by JDBC driver in MyBatis processing
----
SELECT * FROM names
  WHERE id = ?
----

==== Dynamically bindable 2-way SQL

The mybatis-thymeleaf translate a dynamically bindable 2-way SQL that specified by natural template to as follow:

[source,sql]
.Natural template
----
SELECT * FROM names
  WHERE 1 = 1
  /*[# th:if="${not #lists.isEmpty(ids)}"]*/
    AND id IN (
    /*[# th:each="id : ${ids}"]*/
      /*[+ [# th:if="${not idStat.first}"][(',')][/] +]*/
      /*[('#{ids[' + ${idStat.index} + ']}')]*/ 1
    /*[/]*/
    )
  /*[/]*/
  ORDER BY id
----

[source,sql]
.Translated to SQL in Thymeleaf processing (when `ids` is empty)
----
SELECT * FROM names
  WHERE 1 = 1
  ORDER BY id
----

[source,sql]
.Translated to SQL in Thymeleaf processing (when `ids` has 3 elements)
----
SELECT * FROM names
  WHERE 1 = 1
    AND id IN (
      #{ids[0]}
       ,
      #{ids[1]}
       ,
      #{ids[2]}
    )
  ORDER BY id
----

==== Dynamically bindable SQL

The mybatis-thymeleaf translate a dynamically bindable SQL(non 2-way SQL) that specified by template to as follow:

[source,sql]
.Template
----
SELECT * FROM names
  WHERE 1 = 1
  [# th:if="${not #lists.isEmpty(ids)}"]
    AND id IN (
      [# th:each="id : ${ids}"]
        [(${idStat.first} ? '' : ',')]
        [('#{ids[' + ${idStat.index} + ']}')]
      [/]
    )
  [/]
  ORDER BY id
----

This template is simple compare with 2-way SQL, but it cannot execute as-is in SQL execution tool (such as psql, mysql, sqlplus, plugins for IDE, etc...).


=== Mainly Features

The mybatis-thymeleaf provide following features using class that implements
the link:{mybatis-doc-url}/dynamic-sql.html#Pluggable_Scripting_Languages_For_Dynamic_SQL[`LanguageDriver` interface^]
for integrating with template engine provide by Thymeleaf.

* Can write 2-way SQL/dynamic SQL
* Can use a 2-way SQL/dynamic SQL via an annotation and mapper xml
* Can read an SQL template from a template file on classpath
* Can use a custom dialect(attribute tag and expression utility method) at a template
* Can fully customize a template engine configuration


== Requirements

The mybatis-thymeleaf supports using on following Java and artifacts version.

=== Java

* Java 8, Java 11+

[NOTE]
====
About tested versions see the latest link:{travis-ci-url}[Travi CI^] build result.
====

=== MyBatis

* MyBatis 3.4.3+

[NOTE]
====
As basically policy, we do test using following versions.

* latest release version on 3.4.x line
* latest release version on 3.5.x line
* latest snapshot version on 3.5.x line
====

=== Thymeleaf

* Thymeleaf 3.0+

[NOTE]
====
As basically policy, we do test using following versions.

* latest release version on 3.0.x line
====

== Getting Started

In this chapter, we explain basic usage of the mybatis-thymeleaf.

=== Installation

==== Maven

If you are using the Maven as build tool, you can add as follow:

[source,xml,subs="specialchars,attributes"]
.pom.xml (dependencies)
----
<dependency>
  <groupId>org.mybatis</groupId>
  <artifactId>mybatis</artifactId>
  <version>3.4.6</version> <!-- Adjust to your application -->
</dependency>
<dependency>
  <groupId>org.mybatis.scripting</groupId>
  <artifactId>mybatis-thymeleaf</artifactId>
  <version>{revnumber}</version>
</dependency>
----

If you use a snapshot version, you need add the configuration
for using the "Sonatype OSS Snapshots Repository" as follow:

[source,xml,subs="specialchars,attributes"]
.pom.xml (repositories)
----
<repositories>
  <!-- ... -->
  <repository>
    <id>sonatype-oss-snapshots</id>
    <name>Sonatype OSS Snapshots Repository</name>
    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
  </repository>
</repositories>
```
----

==== Gradle

If you are using the Gradle as build tool, you can add as follow:

[source,groovy,subs="specialchars,attributes"]
.build.gradle (dependencies)
----
dependencies {
  // ...
  compile("org.mybatis:mybatis:3.4.6") // Adjust version to your application
  compile("org.mybatis.scripting:mybatis-thymeleaf:{revnumber}")
}
----

If you use a snapshot version, you need add the configuration for using the "Sonatype OSS Snapshots Repository" as follow:

[source,groovy,subs="specialchars,attributes"]
.build.gradle (repositories)
----
repositories {
  // ...
  maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
}
----

=== Configuration

Set the `ThymeleafLanguageDriver` as your default scripting language to MyBatis.

[source,java]
.Configuration class (Java based configuration)
----
Configuration configuration = new Configuration();
configuration.setDefaultScriptingLanguage(ThymeleafLanguageDriver.class);
----

[source,xml]
.mybatis-config.xml (XML based configuration)
----
<settings>
  <setting name="defaultScriptingLanguage"
           value="org.mybatis.scripting.thymeleaf.ThymeleafLanguageDriver"/>
</settings>
----

=== Creating Mapper

The MyBatis provides two ways(annotation driven and XML driven) for creating a Mapper.

==== Annotation driven mapper

If you use the annotation driven mapper, you can specify a 2-way SQL as follow:

[source,java]
.src/main/java/com/example/NameMapper.java
----
public class NameMapper {
  @Select("SELECT * FROM names WHERE id = /*[('#{id}')]*/ 1")
  Name findById(@Param("id") Integer id);
}
----

[TIP]
====

You can specify a 2-way SQL in annotation using "link:https://openjdk.java.net/jeps/326[Raw String Literals^]" feature that support by future JDK version as follow:

[source,java]
----
@Select(``
  SELECT * FROM names
    WHERE id = /*[('#{id}')]*/ 1
``)
Name findById(@Param("id") Integer id);
----

There is a good compatibility for annotation driven mapper.
====

Also, you can specify a 2-way SQL on template file(e.g. `/NameMapper/findById.sql` on class path) as follow:

[source,java]
----
@Select("/NameMapper/findById.sql")
Name findById(@Param("id") Integer id);
----

By default behavior, the mybatis-thymeleaf read a specified template file from just under classpath.

[[_getting-started-template-sql]]
[source,sql]
.src/main/resources/NameMapper/findById.sql
----
SELECT * FROM names
  WHERE id = /*[('#{id}')]*/ 1
----

==== XML driven mapper

If you use the XML driven mapper, you can specify a 2-way SQL as follow:

[source,java]
.src/main/java/com/example/NameMapper.java
----
public class NameMapper {
  Name findById(@Param("id") Integer id);
}
----

[source,xml]
.src/main/resources/com/example/NameMapper.xml
----
<select id="findById" resultType="com.example.Name">
  SELECT * FROM names
    WHERE id = /*[('#{id}')]*/ 1
</select>
----

Also, you can specify a 2-way SQL on template file
(see '<<_getting-started-template-sql,Annotation driven mapper>>' section) as follow:

[source,xml]
----
<select id="findById" resultType="com.example.Name">
  /NameMapper/findById.sql
</select>
----

== Configuration

In this chapter, we explain a way for applying mybatis-thymeleaf to the MyBatis in detail.
About MyBatis core module configuration,
please see the {mybatis-doc-url}/configuration.html[MyBatis reference document^].

=== Basic configuration

You configure to use the `org.mybatis.scripting.thymeleaf.ThymeleafLanguageDriver` as scripting language driver.

==== Java based configuration

[source,java]
.Configuration class
----
Configuration configuration = new Configuration();
configuration.setDefaultScriptingLanguage(ThymeleafLanguageDriver.class); // <1>
// ...
SqlSessionFactory sqlSessionFactory = new SqlSessionFactoryBuilder().build(configuration);
----

<1> Set the `ThymeleafLanguageDriver` class to a `Configuration` instance as default scripting language driver

==== XML based configuration

[source,xml]
.src/main/resources/mybatis-config.xml
----
<settings>
  <setting name="defaultScriptingLanguage"
           value="org.mybatis.scripting.thymeleaf.ThymeleafLanguageDriver"/> // <1>
</settings>
----

[source,java]
----
SqlSessionFactory sqlSessionFactory;
try (Reader configReader = Resources.getResourceAsReader("mybatis-config.xml")) {
  sqlSessionFactory = new SqlSessionFactoryBuilder().build(configReader);
}
----

<1> Set the `ThymeleafLanguageDriver` class to the `defaultScriptingLanguage` of setting item in configuration XML file

=== Customizing configuration

The mybatis-thymeleaf provides three ways for customizing template engine configuration.

* <<Using properties file>>
* <<Using functional interface>>
* <<Using user-defined template engine>>

==== Using properties file

The mybatis-thymeleaf provide the special properties file for customizing default configuration.
By default behavior, the mybatis-thymeleaf load the `mybatis-thymeleaf.properties` stored just under classpath.
About supported properties, please see the <<Configuration properties>>.

===== Using an any properties file

You can use an any properties file instead of the default properties file.
If you use an any properties file, please specify a properties file using
the special system properties(`mybatis-thymeleaf.config.file`) as follow:

[source,text]
----
$ java -Dmybatis-thymeleaf.config.file=mybatis-thymeleaf_production.properties ...
----

===== Using an any file encoding

You can use an any file encoding instead of the default file encoding(`UTF-8`).
If you use an any file encoding, please specify a file encoding using
the special system properties(`mybatis-thymeleaf.config.encoding`) as follow:

[source,text]
----
$ java -Dmybatis-thymeleaf.config.encoding=Windows-31J ...
----

==== Using functional interface

The mybatis-thymeleaf provide the special functional
interface(`org.mybatis.scripting.thymeleaf.TemplateEngineCustomizer`) for customizing configurations using Java code.
This feature provide an opportunity to customize configuration that cannot customize it using properties file.

[source,java]
.src/main/java/com/example/MyTemplateEngineCustomizer.java
----
public class MyTemplateEngineCustomizer implements TemplateEngineCustomizer {
  @Override
  public void customize(TemplateEngine defaultTemplateEngine) {
    // ... <1>
  }
}
----

[source,properties]
.src/main/resources/mybatis-thymeleaf.properties
----
customizer = com.example.MyTemplateEngineCustomizer # <2>
----

<1> Write a Java code for customizing template engine

<2> Specify a FQCN of customizer class in `mybatis-thymeleaf.properties`

==== Using user-defined template engine

When your application requirements cannot be satisfied using above customizing features,
you can apply a user-defined template engine(full managed template engine) to the mybatis-thymeleaf as follow:

[source,java]
.Configuration class
----
TemplateEngine templateEngine = new TemplateEngine(); // <1>
templateEngine.addDialect(new MyBatisDialect());
templateEngine.setEngineContextFactory(new MyBatisIntegratingEngineContextFactory(
    targetTemplateEngine.getEngineContextFactory()));
// ...

Configuration configuration = new Configuration();
configuration.getLanguageRegistry()
    .register(ThymeleafLanguageDriver.newBuilder().templateEngine(templateEngine).build()); // <2>
configuration.setDefaultScriptingLanguage(ThymeleafLanguageDriver.class); // <3>
----

<1> Create an instance of class that implements `org.thymeleaf.ITemplateEngine`

<2> Register an instance of `ThymeleafLanguageDriver` that associate with user-defined template engine instance

<3> Set the `ThymeleafLanguageDriver` class as default scripting language driver

== Writing 2-way SQL

In this section, we explain standard usage of 2-way SQL.

[CAUTION]
====
About cautions for usage 2-way SQL, please see the <<Cautions for usage>>.
====


=== Binding value

The mybatis-thymeleaf use the default binding feature provided by MyBatis core module.

[source,sql]
.About default binding feature provided by MyBatis
----
SELECT * FROM names
  WHERE id = #{id} -- <1>
----

<1> A bind value is specified by `#{variable name}` format

Therefore, you need to write a 2-way SQL template for generating string
that can be parsed by MyBatis core module as follow:


[source,sql]
.2-way SQL template for generating string that can be parsed by MyBatis core module
----
SELECT * FROM names
  WHERE id = /*[('#{id}')]*/ 1 -- <1>
----

<1> A bind value specify by `/\*[('#{variable name}')]*/` format

[NOTE]
====
**What can you bind?**

Basically, you can bind a parameter object(Mapper method arguments or `SqlSession` method arguments).
In addition, the mybatis-thymeleaf allow to be bind a registered value using `mybatis:bind` tag.
About usage of `mybatis:bind`, please see <<Attribute tag>>.
====

=== Dynamic SQL

The Thymeleaf supports to create an any string dynamically using conditional evaluation
and iterating evaluation feature. By using this feature, you can write a dynamic 2-way SQL.

* <<Using tag for specifying condition>>
* <<Using tag for iteration>>

==== Using tag for specifying condition

If you add a SQL part when any condition is matches or not, you can use following attribute tags.

* `th:if`
* `th:unless` (denial version for `th:if`)
* `th:switch`
* `th:case`

[source,sql]
.Usage of conditional attribute tag on WHERE
----
SELECT * FROM names
  WHERE 1 = 1 -- <1>
  /*[# th:if="${firstName} != null"]*/ -- <2>
    AND firstName = /*[('#{firstName}')]*/ 'Taro' -- <3>
  /*[/]*/ -- <4>
  ORDER BY id
----

[source,sql]
.Usage of conditional attribute tag on SET
----
UPDATE names
  SET id = id -- <5>
  /*[# th:if="${firstName} != null"]*/
    , firstName = /*[('#{firstName}')]*/ 'Taro'
  /*[/]*/
  WHERE id = /*[('#{id}')]*/ 1
----

<1> Specify a non-dynamic condition at first position because the mybatis-thymeleaf does not provide
    the trimming feature such as `<where>` of XML based scripting language

<2> Specify a condition on start tag using natural template

<3> Specify a 2-way SQL of binding value

<4> Specify an end tag of condition

<5> Specify a non-dynamic updating column at first position because the mybatis-thymeleaf does not provide
    the trimming feature such as `<set>` of XML based scripting language

==== Using tag for iteration

The Thymeleaf supports to process for iteration object(`List` etc..) using `th:each`.

[source,sql]
.Usage of iteration
----
SELECT * FROM names
  WHERE 1 = 1
  /*[# th:if="${not #lists.isEmpty(ids)}"]*/
    AND id IN (
    /*[# th:each="id : ${ids}"]*/ -- <1>
      /*[+ [# th:if="${not idStat.first}"][(',')][/] +]*/ -- <2>
      /*[('#{ids[' + ${idStat.index} + ']}')]*/ 1 -- <3>
    /*[/]*/ -- <4>
    )
  /*[/]*/
  ORDER BY id
----

<1> Specify an iterable object on `th:each`

<2> Append comma character when element position is not first

<3> Specify a 2-way SQL of binding value per iterable element.
    A bind value specify by `/*[('#{variable name[index]}')]` format.

<4> Specify an end tag of iteration

Also, you can use the custom expression utility method provided by the mybatis-thymeleaf
instead of standard dialect. For details, please see <<Expression utility method>>.

[source,sql]
.Use the custom expression utility method for appending comma
----
SELECT * FROM names
  WHERE 1 = 1
  /*[# th:if="${not #lists.isEmpty(ids)}"]*/
    AND id IN (
    /*[# th:each="id : ${ids}"]*/
      /*[(${#mybatis.commaIfNotFirst(idStat)})]*/ -- <1>
      /*[('#{ids[' + ${idStat.index} + ']}')]*/ 1
    /*[/]*/
    )
  /*[/]*/
  ORDER BY id
----

[source,sql]
.Use the custom expression utility method for creating bind variables string of IN clause
----
SELECT * FROM names
  WHERE 1 = 1
  /*[# th:if="${not #lists.isEmpty(ids)}"]*/
    AND id IN (/*[(${#mybatis.inClauseBindVariables('ids', ids.size())})]*/ 1) -- <2>
  /*[/]*/
  ORDER BY id
----

<1> Can use the `#mybatis.commaIfNotFirst(IterationStatusVar)` method instead of standard dialect
<2> Can use the `#mybatis.inClauseBindVariables(String, int)` method instead of standard dialect or above utility method


=== Fragment

The Thymeleaf supports to insert template string from an another template file.
By using this feature, you can share a 2-way SQL on multiple SQL template.

The standard use case using this feature is paging query as follow:

[source,java]
.Mapper
----
// Count a total record number that matches for criteria
@Select("/NameMapper/countByCriteria.sql")
long countByCriteria(@Param("criteria") NameCriteria criteria);

// Search records that matches for criteria and specified page
@Select("/NameMapper/findPageByCriteria.sql")
List<Name> findPageByCriteria(@Param("criteria") NameCriteria criteria, @Param("pageable") Pageable pageable);
----

.src/main/resources/NameMapper/countByCriteria.sql
[source,sql]
----
SELECT COUNT(*) FROM names
  WHERE 1 = 1
  /*[# th:if="${criteria.firstName} != null"]*/
    AND firstName = /*[('#{criteria.firstName}')]*/ 'Taro'
  /*[/]*/
  /*[# th:if="${criteria.lastName} != null"]*/
    AND lastName = /*[('#{criteria.lastName}')]*/ 'Yamada'
  /*[/]*/
----

.src/main/resources/NameMapper/findPageByCriteria.sql
[source,sql]
----
SELECT * FROM names
  WHERE 1 = 1
  /*[# th:if="${criteria.firstName} != null"]*/
    AND firstName = /*[('#{criteria.firstName}')]*/ 'Taro'
  /*[/]*/
  /*[# th:if="${criteria.lastName} != null"]*/
    AND lastName = /*[('#{criteria.lastName}')]*/ 'Yamada'
  /*[/]*/
  LIMIT /*[('#{pageable.pageSize}')]*/ 20
  OFFSET /*[('#{pageable.offset}')]*/ 0
  ORDER BY id
----

Probably looking at above SQLs many developers will look for a way to share the `WHERE` clause.
In such case, you can share any SQL part by multiple SQL using fragment feature.

==== Creating a fragment SQL

At first, you create a fragment SQL template file for sharing by multiple SQL as follow:

.src/main/resources/NameMapper/whereByCriteria.sql
[source,sql]
----
  WHERE 1 = 1
  /*[# th:if="${criteria.firstName} != null"]*/
    AND firstName = /*[('#{criteria.firstName}')]*/ 'Taro'
  /*[/]*/
  /*[# th:if="${criteria.lastName} != null"]*/
    AND lastName = /*[('#{criteria.lastName}')]*/ 'Yamada'
  /*[/]*/
----

==== Insert a fragment SQL

You can insert a fragment SQL template file on each template as follow:

.src/main/resources/NameMapper/countByCriteria.sql
[source,sql]
----
SELECT COUNT(*) FROM names
  /*[# th:insert="~{/NameMapper/whereByCriteria.sql}" /]*/ -- <1>
----

.src/main/resources/NameMapper/findPageByCriteria.sql
[source,sql]
----
SELECT * FROM names
  /*[# th:insert="~{/NameMapper/whereByCriteria.sql}" /]*/ -- <1>
  LIMIT /*[('#{pageable.pageSize}')]*/ 20
  OFFSET /*[('#{pageable.offset}')]*/ 0
  ORDER BY id
----

<1> Insert a fragment SQL template file

=== Special variables

The mybatis and mybatis-thymeleaf provides special variables that prefixed with `_` as follows:

[cols="2,7,1",options="header"]
.Special variables
|===
^|Variable Name
^|Description
^|Type

|`_parameter`
|The parameter object that passed to the MyBatis
|Any type

|`_databaseId`
|The id for identifying the database
(If you want to this variable, you should be enabled the link:{mybatis-doc-url}/configuration.html#databaseIdProvider[`DatabaseIdProvider` feature^] on MyBatis)
|`String`

|`_customBindVariables`
a|The custom bind variables that registered using <<mybatis-bind,bind>>

[CAUTION]
====
This variable used by internal processing on the mybatis-thymeleaf.
Therefore, we *don't recommend* using this variable within the your application.
====

|`Map<String, Object>`

|`_fallbackParameterObject`
a|Whether can access by any variable name for value object that specified as parameter object.

[CAUTION]
====
This variable used by internal processing on the mybatis-thymeleaf.
Therefore, we *don't recommend* using this variable within the your application.
====

|`boolean`
|===

=== Using configuration properties

You can access the configuration properties of MyBatis from your SQL template.
About configuration properties, please see the link:{mybatis-doc-url}/configuration.html#properties[MyBatis reference documentation^].

[source,java]
.Java based configuration
----
Configuration configuration = new Configuration();
Properties variables = new Properties();
variables.setProperty("tableNameOfUser", "accounts"); // <1>
configuration.setVariables(variables);
----

[source,xml]
.XML based configuration (mybatis-config.xml)
----
<properties>
  <property name="tableNameOfUser" value="accounts"/> <!--1-->
</properties>
----

[source,sql]
.SQL template
----
SELECT * FROM /*[(${tableNameOfUser} ?: 'users')]*/ users -- <2>
----

<1> Define an any property as MyBatis's configuration properties
<2> Access a configuration property using Thymeleaf's expression

Above SQL template translate to as follows:

[source,sql]
.Translated SQL (when `tableNameOfUser` is defined)
----
SELECT * FROM accounts
----

[source,sql]
.Translated SQL (when `tableNameOfUser` is not defined)
----
SELECT * FROM users
----


== Cautions for usage

[CAUTION]
====
The Thymeleaf 3 does not provide the template mode for SQL.
Therefore there are some cautions for usage.
====

=== 2-way SQL format

If you use a binding value using 2-way SQL format,
there is case that cannot translate correctly 2-way SQL when specify multiple item on one line as follow:

[source,sql]
.Invalid format
----
SELECT * FROM names
  WHERE id = /*[('#{id}')]*/ 1 AND version = /*[('#{version}')]*/ 1
----

You can resolve it that add a line break chars between with each conditions as follow:

[source,sql]
.Valid format
----
SELECT * FROM names
  WHERE id = /*[('#{id}')]*/ 1 -- <1>
  AND version = /*[('#{version}')]*/ 1
----

<1> Add the line break chars(LF or CRLF) between with each conditions

Alternatively, you can resolve it that specify the empty comment between with each conditions as follow:

[source,sql]
.Valid format
----
SELECT * FROM names
  WHERE id = /*[('#{id}')]*/ 1 /**/ AND version = /*[('#{version}')]*/ 1 -- <1>
----

<1> Add the empty SQL comment(`/**/`) between each conditions

[NOTE]
====
We known that threre is no problem using on `VALUES` and `SET` clause as follows:

[source,sql]
.Valid format on VALUES
----
INSERT INTO names (firstName, lastName)
  VALUES (/*[('#{firstName}')]*/ 'Taro' ,/*[('#{lastName}')]*/ 'Yamada')
----

[source%nowrap,sql]
.Valid format on SET
----
UPDATE names
  SET firstName = /*[('#{firstName}')]*/ 'Taro' ,lastName = /*[('#{lastName}')]*/ 'Yamada'
  WHERE id = /*[('#{id}')]*/ 1
----

However, the following 2-way SQL is invalid.

[source,sql]
.Invalid format
----
UPDATE names
  SET firstName = /*[('#{firstName}')]*/ 'Taro'
     ,lastName = /*[('#{lastName}')]*/ 'Yamada' WHERE id = /*[('#{id}')]*/ 1 -- <1>
----

<1> Cannot specify the `WHERE` clause after the 2-way SQL on same line
    (Even in this case, you can resolve it that specify the empty comment(`/**/`) before the `WHERE` clause)

====

=== Using '\'(backslash)

If you are using 2-way SQL mode, there is case that cannot parse a 2-way SQL when specify `'\'`(backslash) within static template parts.
We know that following case cannot be parsed 2-way SQL. If you are not using 2-way SQL mode, this limitation can be ignore.

==== ESCAPE clause for LIKE

If you specify the `ESCAPE '\'` directly as static template parts, the Thymeleaf cannot parse it.

[source,sql]
.Invalid usage
----
/*[# mybatis:bind="patternFirstName=|${#mybatis.escapeLikeWildcard(firstName)}%|" /]*/
AND firstName LIKE /*[('#{patternFirstName}')]*/ 'Taro%' /**/ ESCAPE '\'
----

<1> Specify the `ESCAPE '\'` directly as static template parts

[TIP]
====
As a solution for avoiding this behavior,
the mybatis-thymeleaf provide the expression utility method for adding the `ESCAPE` clause.
For detail, please see <<likeEscapeClause>>.
====

== Custom Dialect

The mybatis-thymeleaf provide the custom dialect class(`org.mybatis.scripting.thymeleaf.MyBatisDialect`)
that help for generating dynamic SQL.

=== Attribute tag

By default, you can use it using `mybatis` dialect prefix.

[cols="2,4,4",options="header"]
.Supported method list
|===
^|Attribute Tag Name
^|Description
^|Attribute Value Format

|<<mybatis-bind,bind>>
|Register an any value to the MyBatis's bind variables
(Provides a feature similar to that of the link:{mybatis-doc-url}/dynamic-sql.html#bind[`<bind>`^] provided by MyBatis core module)
a|{variable name}={variable value}(,...) +
 +
 Valid format is same with `th:with` provided by Thymeleaf.
|===

[[mybatis-bind]]
==== bind

[source,sql]
.Basic usage:
----
SELECT * FROM names
  WHERE 1 = 1
  /*[# th:if="${firstName} != null"]*/
    /*[# mybatis:bind="patternFirstName=|${#mybatis.escapeLikeWildcard(firstName)}%|" /]*/ -- <1>
    AND firstName LIKE /*[('#{patternFirstName}')]*/ 'Taro' -- <2>
  /*[/]*/
----

[source,sql]
.Usage for registering multiple variables:
----
/*[# mybatis:bind="patternFirstName=|${#mybatis.escapeLikeWildcard(firstName)}%|, patternLastName=|${#mybatis.escapeLikeWildcard(lastName)}%|" /]*/ -- <3>
----

<1> Register an any value(e.g. editing value at template) as custom bind variables
<2> Bind a custom bind variable
<3> Also, you can register multiple custom bind variables separating with comma at the same time

[NOTE]
====
*Why need the bind tag?*

The binding feature provide by MyBatis cannot access a variable that shared by the `th:with`
because it can only access within a template. Hence, the mybatis-thymeleaf provide the `bind` attribute tag.
====

=== Expression utility method

By default, you can access it using `#mybatis` expression.

[cols="1,5a,4",options="header"]
.Supported method list
|===
^|Method
^|Arguments
^|Description

|<<mybatis-commaIfNotFirst,commaIfNotFirst>>
|

[cols="^1,4,5",options="header"]
!===
^!No
^!Type
^!Description

!1
!IterationStatusVar
!A current iteration status
!===

|Return the comma if a current iteration status is not first

|<<mybatis-commaIfNotLast,commaIfNotLast>>
|

[cols="^1,4,5",options="header"]
!===
^!No
^!Type
^!Description

!1
!IterationStatusVar
!A current iteration status
!===

|Return the comma if a current iteration status is not last

|<<mybatis-inClauseBindVariables,inClauseBindVariables>>
|

[cols="^1,4,5",options="header"]
!===
^!No
^!Type
^!Description

!1
!String
!A bind variable name for target iteration object

!2
!int
!A element size of target iteration object

!3
!boolean
!Whether enclose with "(" and ")"
(If this argument is omit, it become result same with specifying `false`)
!===

a|Return a bind variables string for IN clause

* If enclose is `true`, return a string like `"(#{ids[0]}, #{ids[1]})"`
* If enclose is `false`(or omit), return a string like `"#{ids[0]}, #{ids[1]}"`

|<<mybatis-escapeLikeWildcard,escapeLikeWildcard>>
|

[cols="^1,4,5",options="header"]
!===
^!No
^!Type
^!Description

!1
!String
!A target value
!===

|Return a value that escaped a wildcard character of LIKE condition
(By default behavior, this method escape the `"%"`, `"_"` and `"\"`(escape character itself) using `"\"`)

|<<mybatis-likeEscapeClause,likeEscapeClause>>
| N/A
|Return a escape clause string of LIKE condition
( By default behavior, this method return `" ESCAPE '\' "`)
|===


[TIP]
====
You can customize the default behavior for the `escapeLikeWildcard` and `likeEscapeClause`
using <<Configuration properties, Configuration properties>>.
====


[[mybatis-commaIfNotFirst]]
==== commaIfNotFirst

[source,sql]
.Basic usage:
----
id IN (
/*[# th:each="id : ${ids}"]*/
  /*[(${#mybatis.commaIfNotFirst(idStat)})]*/ -- <1>
  /*[('#{ids[' + ${idStat.index} + ']}')]*/ 1
/*[/]*/
)
----

<1> Avoid adding comma at the first element

[source,sql]
.Translate to:
----
id IN (

  #{ids[0]}
  ,
  #{ids[1]}
)
----

[[mybatis-commaIfNotLast]]
==== commaIfNotLast

[source,sql]
.Basic usage:
----
id IN (
/*[# th:each="id : ${ids}"]*/
  /*[('#{ids[' + ${idStat.index} + ']}')]*/ 1
  /*[(${#mybatis.commaIfNotLast(idStat)})]*/ -- <1>
/*[/]*/
)
----

<1> Avoid adding comma at the last element

[source,sql]
.Translate to:
----
id IN (
  #{ids[0]}
  ,
  #{ids[1]}

)
----


[[mybatis-inClauseBindVariables]]
==== inClauseBindVariables

[source,sql]
.Basic usage:
----
/*[# th:if="${not #lists.isEmpty(ids)}"]*/
  AND id IN (/*[(${#mybatis.inClauseBindVariables('ids', ids.size())})]*/ 1) -- <1>
/*[/]*/
----

<1> Create bind variables string for IN clause with specifying target iteration object

[source,sql]
.Translate to:
----
  AND id IN (#{ids[0]}, #{ids[1]})
----


[[mybatis-escapeLikeWildcard]]
==== escapeLikeWildcard

[source,sql]
.Basic usage:
----
/*[# th:if="${firstName} != null"]*/
  /*[# mybatis:bind="patternFirstName=|${#mybatis.escapeLikeWildcard(firstName)}%|" /]*/ -- <1>
  AND firstName LIKE /*[('#{patternFirstName}')]*/ 'Taro%'
/*[/]*/
----

<1> Register a value that escaped wildcard character of LIKE condition as custom bind variables

[source,sql]
.Translate to:
----
  AND firstName LIKE #{patternFirstName}
----


[[mybatis-likeEscapeClause]]
==== likeEscapeClause

[source,sql]
.Basic usage:
----
/*[# th:if="${firstName} != null"]*/
  /*[# mybatis:bind="patternFirstName=|${#mybatis.escapeLikeWildcard(firstName)}%|" /]*/
  AND firstName LIKE /*[('#{patternFirstName}')]*/ 'Taro%' /*[(${#mybatis.likeEscapeClause()})]*/ -- <1>
/*[/]*/
----

<1> Add `ESCAPE` clause at template processing time

[source,sql]
.Translate to:
----
  AND firstName LIKE #{patternFirstName} ESCAPE '\'
----

== Using non 2-way SQL mode

The non 2-way SQL is simple a little compare with 2-way SQL and limitations not found at now.

=== Configuration

By default, the mybatis-thymeleaf will be use the 2-way SQL mode.
Therefore you should be configure explicitly to use the non 2-way SQL mode using configuration properties file or builder option as follow:

[source,properties]
.How to configure using configuration properties file(src/main/resources/mybatis-thymeleaf.properties)
----
use-2way = false # <1>
----

<1> Set the `use-2way` to `false`

[source,java]
.How to configure using builder option
----
// ...
configuration.getLanguageRegistry()
    .register(ThymeleafLanguageDriver.newBuilder().use2way(false).build()); // <1>
// ...
----

<1> Set the `use2way` builder option to `false`


=== Binding value

In the non 2-way SQL mode, you use the MyBatis's standard bind variable expression such as `#{...}` as follow:

[source,sql]
.MyBatis's standard bind variable expression
----
SELECT * FROM names WHERE id = #{id}
----

If you bind a iteration object(List etc..) using dynamic SQL,
you need to generate MyBatis's standard bind variable expression using inlined expression of Thymeleaf as follow:

[source,sql]
.Template
----
SELECT * FROM names
  WHERE 1 = 1
  [# th:if="${not #lists.isEmpty(ids)}"]
    AND id IN (
      [# th:each="id : ${ids}"]
        [(${idStat.first} ? '' : ',')]
        [('#{ids[' + ${idStat.index} + ']}')] -- <1>
      [/]
    )
  [/]
  ORDER BY id
----

<1> Generate bind variable expression.

An above template will be translate to following SQL in Thymeleaf processing.

[source,sql]
.Translated to SQL (when `ids` has 3 elements)
----
SELECT * FROM names
  WHERE 1 = 1
    AND id IN (
      #{ids[0]}
      ,
      #{ids[1]}
      ,
      #{ids[2]}
    )
  ORDER BY id
----

=== Different with 2-way SQL mode

The different with 2-way SQL mode is that will be unnecessary to enclose the thymeleaf expressions as SQL comment(`/\*[...]*/`).
In this section, some samples are provide the non 2-way SQL.

==== Using tag for specifying condition

If you add a SQL part when any condition is matches or not, you can use following attribute tags (`th:if`, `th:unless`, `th:switch` and `th:case`).

[source,sql]
.Usage of conditional attribute tag on WHERE
----
SELECT * FROM names
  WHERE 1 = 1
  [# th:if="${firstName} != null"]
    AND firstName = #{firstName}
  [/]
  ORDER BY id
----

[source,sql]
.Usage of conditional attribute tag on SET
----
UPDATE names
  SET id = id
  [# th:if="${firstName} != null"]
    , firstName = #{firstName}
  [/]
  WHERE id = #{id}
----

==== Using tag for iteration

The Thymeleaf supports to process for iteration object(`List` etc..) using `th:each`.

[source,sql]
.Usage of iteration
----
SELECT * FROM names
  WHERE 1 = 1
  [# th:if="${not #lists.isEmpty(ids)}"]
    AND id IN (
      [# th:each="id : ${ids}"]
        [(${idStat.first} ? '' : ',')]
        [('#{ids[' + ${idStat.index} + ']}')]
      [/]
    )
  [/]
  ORDER BY id
----

==== Using custom expression utility method

[source,sql]
.Use the custom expression utility method for creating bind variables string of IN clause
----
SELECT * FROM names
  WHERE 1 = 1
  [# th:if="${not #lists.isEmpty(ids)}"]
    AND id IN (
      [(${#mybatis.inClauseBindVariables('ids', ids.size())})]
    )
  [/]
  ORDER BY id
----

==== Using custom attribute tag

[source,sql]
.Use the custom attribute tag
----
SELECT * FROM names
  WHERE 1 = 1
  [# th:if="${firstName} != null"]
    [# mybatis:bind="patternFirstName=|${#mybatis.escapeLikeWildcard(firstName)}%|" /]
    AND firstName LIKE #{patternFirstName}
  [/]
----

== Usage on framework

In this chapter, we explain ways that integrate with an application framework.

=== Spring Boot

If you are using the {mybatis-spring-boot-doc-url}/mybatis-spring-boot-autoconfigure/index.html[mybatis-spring-boot-starter(Spring Boot)^],
you can configure using configuration properties(properties or yaml file) as follow:

[source%nowrap,properties]
.src/main/resources/application.properties
----
mybatis.configuration.default-scripting-language=org.mybatis.scripting.thymeleaf.ThymeleafLanguageDriver
----

[source,yml]
.src/main/resources/application.yml
----
mybatis:
  configuration:
    default-scripting-language: org.mybatis.scripting.thymeleaf.ThymeleafLanguageDriver
----

Also, you can fully customize a template engine using the `ConfigurationCustomizer`.

[source,java]
.Configuration class
----
@Bean
ConfigurationCustomizer mybatisConfigurationCustomizer() {
  return configuration -> {
    TemplateEngine templateEngine = new TemplateEngine(); // <1>
    templateEngine.addDialect(new MyBatisDialect());
    templateEngine.setEngineContextFactory(new MyBatisIntegratingEngineContextFactory(
      targetTemplateEngine.getEngineContextFactory()));
    // ...
    configuration.getLanguageRegistry().register(
        ThymeleafLanguageDriver.newBuilder().templateEngine(templateEngine).build()); // <2>
    configuration.setDefaultScriptingLanguage(ThymeleafLanguageDriver.class); // <3>
  };
}
----

<1> Create an instance of class that implements `org.thymeleaf.ITemplateEngine`

<2> Register an instance of `ThymeleafLanguageDriver` that associate with user-defined template engine instance

<3> Set the `ThymeleafLanguageDriver` class as default scripting language driver instead of
    specifying as configuration properties


== Appendix

=== Configuration properties

The mybatis-thymeleaf provides following properties for customizing configurations.

[cols="1,6,^1,2",options="header"]
.Supported property list
|===
^|Property Key
^|Description
^|Type
^|Default value

4+|*General configuration*

|`use-2way`
|Whether use the 2-way SQL feature
|`Boolean`
|`true` (enable the 2-way SQL feature)

|`customizer`
|The FQCN of class that implements the `TemplateEngineCustomizer`
(interface for customizing a default TemplateEngine instanced by the mybatis-thymeleaf)
|`Class`
|`null` (This instance is do-nothing)

4+|*Template cache configuration*

|`cache.enabled`
|Whether use the cache feature when load template resource file
|`Boolean`
|`true` (enable template cache feature)

|`cache.ttl`
|The cache TTL(millisecond) for resolved templates
|`Long`
|`null` (no TTL)

4+|*Template file configuration*

|`file.character-encoding`
|The character encoding for reading template resource file
|`String`
|`"UTF-8"`

|`file.base-dir`
|The base directory for reading template resource file
|`String`
|`""` (just under class path)

|`file.patterns`
|The patterns for reading as template resource file
(Can specify multiple patterns using comma(`","`) as separator character)
|`String`
|`"*.sql"`

4+|*Dialect configuration*

|`dialect.like.escape-char`
|The escape character for wildcard of LIKE condition
|`Character`
|`'\'` (backslash)

|`dialect.like.escape-clause-format`
|The format of escape clause for LIKE condition
(Can specify format that can be allowed by `String#format` method)
|`String`
|`" ESCAPE '%s' "`

|`dialect.like.additional-escape-target-chars`
|Additional escape target characters(custom wildcard characters) for LIKE condition
(Can specify multiple characters using comma(`","`) as separator character)
|`String`
|`""` (no specify)
|===

[source,properties]
.src/main/resources/mybatis-thymeleaf.properties
----
use-2way = true
customizer = com.example.MyTemplateEngineCustomizer
cache.enabled = true
cache.ttl = 3600000
file.character-encoding = UTF-8
file.base-dir = /templates/sqls
file.patterns = *sql, *.sql.template
dialect.like.escape-char = ~
dialect.like.escape-clause-format = escape '%s'
dialect.like.additional-escape-target-chars = ％, ＿
----

[TIP]
====
These properties can be specified via builder class of `ThymeleafLanguageDriver` as follow:

[source,java]
----
// ...
configuration.getLanguageRegistry().register(ThymeleafLanguageDriver.newBuilder()
    .use2way(true)
    .customizer(CustomTemplateEngineCustomizer.class)
    .cacheEnabled(true)
    .cacheTtl(3600000)
    .fileCharacterEncoding(StandardCharsets.UTF_8)
    .fileBaseDir("/templates/sqls")
    .filePatterns("*.sql", "*.sql.template")
    .dialectLikeEscapeChar('~')
    .dialectLikeEscapeClauseFormat("escape '%s'")
    .dialectLikeAdditionalEscapeTargetChars('％' , '＿')
    .build());
// ...
----

If you specify the value both with properties file and builder option, the properties file value applied.
====
